services:
  postgres: 
    image: postgres:latest
    container_name: postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-root}
      - POSTGRES_DB=${POSTGRES_DB:-my_database}
    volumes:
      # CORREÇÃO: Caminho atualizado para a imagem oficial do Postgres
      - polls_pg_data:/var/lib/postgresql

    healthcheck:
      # CORREÇÃO: Passando o usuário dinamicamente para evitar falhas se mudar o .env
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER:-postgres} -d $${POSTGRES_DB:-my_database}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app_network

  firebase_emulator:
    image: andreysenov/firebase-tools:latest
    container_name: firebase_emulator
    ports:
      - "4000:4000"
      - "9099:9099"
      - "8080:8080"
      - "9199:9199"
    volumes:
      - .:/home/node/app
      - ${PATH_SECURITY_CREDENTIALS_DIR}:/home/node/SecurityInformations
    working_dir: /home/node/app
    environment:
      - FIREBASE_TOKEN=token_falso_para_evitar_o_aviso
    # Removida a flag --host inválida
    command: firebase emulators:start --project=demo-local --config=/home/node/SecurityInformations/firebase.json --import=/home/node/app/firebase_data --export-on-exit
    networks:
      - app_network

  fastapi:
    build: .
    container_name: "fastapi_app"
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ${PATH_SECURITY_CREDENTIALS_DIR}:/root/.SecurityInformations 
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-root}@postgres:5432/${POSTGRES_DB:-my_database}
      - PATH_FIREBASE_CREDENTIALS=${PATH_FIREBASE_CREDENTIALS}    
    depends_on:
      postgres:
        condition: "service_healthy"
    networks:
      - app_network

    command: uv run fastapi dev app/main.py --host 0.0.0.0 --port 8000

networks:
  app_network:
    driver: bridge
    
volumes:
  polls_pg_data:
