[project]
name = "tst-backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "email-validator>=2.3.0",
    "fastapi[standard]>=0.136.1",
    "firebase-admin>=7.4.0",
    "psycopg2-binary>=2.9.12",
    "pydantic-extra-types>=2.11.1",
    "pytest>=9.0.3",
    "sqlalchemy[postgresql-psycopgbinary]>=2.0.49",
]

[tool.pytest.ini_options]
pythonpath = ["."]
testpaths = ["tests"]

[tool.uv]
package = true